In [3]:
import numpy as np
listem = [1,2,3]
type(listem)

list

In [5]:
dizim = np.array(listem)
type(dizim)

numpy.ndarray

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
dizi = np.random.randint(0,10,5)
dizi

array([2, 0, 4, 0, 6])

In [38]:
print(dizi.max())        #dizideki en büyük sayı
print(dizi.argmax())     #dizideki en büyük sayının indisi
print(dizi.min())        #dizideki en küçük sayı
print(dizi.argmin())     #dizideki en küçük sayının indisi
print(dizi.mean())       #dizinin ortalamasını bulur
print(dizi.shape)        #dizinin boyutunu verir

6
4
0
1
2.4
(5,)


In [45]:
print(dizi.reshape(1,5))

[[2 0 4 0 6]]


In [55]:
dizii = np.arange(0,25).reshape(5,5)
print(dizii.shape)
print(dizii)

(5, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [81]:
print(dizii[0])
print("---------------")
print(dizii[:2])
print("---------------")
print(dizii[:,-1])
print("---------------")
print(dizii[:,1])


[0 1 2 3 4]
---------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
---------------
[ 4  9 14 19 24]
---------------
[ 1  6 11 16 21]
