In [23]:
#Örnek 2.26 – Bitwise işlemleri -2

import numpy as np

x = np.array([[8,10,12],[11,7,3],[1,15,2]])
y = np.array([[1,2,1]])

print(x)
print("*****")
print(y)
print("*****")
print(x+y)
print("*****")
print(x.shape)
print("*****")
print(y.shape)

[[ 8 10 12]
 [11  7  3]
 [ 1 15  2]]
*****
[[1 2 1]]
*****
[[ 9 12 13]
 [12  9  4]
 [ 2 17  3]]
*****
(3, 3)
*****
(1, 3)


In [16]:
import numpy as np
 
a = np.array([
    [1],
    [2]
])
b = np.array([
    [3, 4],
    [5, 6]
])
c = np.array([
    [1, 2]
])
print("******")
print(a.shape)
print(b.shape)
print(c.shape)
print("******")
# Ayni satir sayisi
# Farkli sutun sayisi
# ama a'nin boyutu bir sutun o yuzden calisir
print(a * b)
# [[ 3, 4],
# [10, 12]]
print("******")
# Ayni sutun sayisi
# Farkli satir sayisi
# ama c bir satirli o yuzden calisir
print(b * c)
# [[ 3, 8],
# [5, 12]]
print("******")
# Farkli satir sayisi
# Farkli sutun sayisi
# ama a da c de tek boyutlu o yuzden calisir
print(a + c)
# [[2, 3],
# [3, 4]]

******
(2, 1)
(2, 2)
(1, 2)
******
[[ 3  4]
 [10 12]]
******
[[ 3  8]
 [ 5 12]]
******
[[2 3]
 [3 4]]


In [19]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  

print(a.shape)
print(b.shape)
print("******")
print(a) 
print("******")  
print(b) 
print("******")  
print(a + b)
print("******")
print((a + b).shape)

(4, 3)
(3,)
******
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
******
[1. 2. 3.]
******
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
******
(4, 3)


In [33]:
import numpy as np 

a = np.array([[1,1],[1,1]],dtype=np.int8) 
b = np.array([10,20,30,40]) 

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
??np.double

Init signature: np.double(self, /, *args, **kwargs)
Docstring:     
Double-precision floating-point number type, compatible with Python `float`
and C ``double``.
Character code: ``'d'``.
Canonical name: ``np.double``.
Alias: ``np.float_``.
Alias *on this platform*: ``np.float64``: 64-bit precision floating-point number type: sign bit, 11 bits exponent, 52 bits mantissa.
File:           c:\users\murat\anaconda3\envs\python-ahi\lib\site-packages\numpy\__init__.py
Type:           type
Subclasses:     
