In [86]:
#Örnek 2.26 – np.minumum() ve np.maximum() kullanımı

import numpy as np

x = np.minimum([6, 5, 3], [5, 6, 8])
y = np.maximum([6, 5, 3], [5, 6, 8])
z = np.minimum([[6, 5, 3], [5, 6, 8]],[2,9,1])
t = np.minimum([5., 3.],[2., 7.],where=[True,False])
print(x)
print(y)
print(z)
print(t)

[5 5 3]
[6 6 8]
[[2 5 1]
 [2 6 1]]
[2. 3.]
