In [42]:
#Örnek 2.22 – np.split() fonksiyonu

import numpy as np

x = np.arange(5.0)*2
y = np.arange(25.0).reshape(5,5)

print(x)
print("*****")
print(y)
print("*****")
print(x[3])
print("*****")
print(y[3,2]) #print(y[3][2])
print("*****")
print(y[1])
print("*****")
print(x[1:3])
print("*****")
print(y[1:3])
print("*****")
print(x[np.array([4, 2, 1])])
print("*****")
print(y[3:5,2:4])
print("*****")
print(y[:,1:3])
print("*****")
print(y[:2,3:])
print("*****")
print(y[4,1::3])
print("*****")
print(y[::2,0])

[0. 2. 4. 6. 8.]
*****
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
*****
6.0
*****
17.0
*****
[5. 6. 7. 8. 9.]
*****
[2. 4.]
*****
[[ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
*****
[8. 4. 2.]
*****
[[17. 18.]
 [22. 23.]]
*****
(5, 2)
*****
[[3. 4.]
 [8. 9.]]
*****
[21. 24.]
*****
[ 0. 10. 20.]
