In [39]:
#Örnek 2.21 – np.split() fonksiyonu

import numpy as np

x = np.arange(9.0)
print(np.split(x, 3))
print("******")
print(np.split(x, [2,5,7]))
print("******")
y = np.arange(16.0).reshape(4,4)
print(y)
print("******")
print(np.vsplit(y, 2)) #print(np.split(y, 2, axis=0))
print("******")
print(np.hsplit(y, 2)) #print(np.split(y, 2, axis=1))

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]
******
[array([0., 1.]), array([2., 3., 4.]), array([5., 6.]), array([7., 8.])]
******
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
******
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
******
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]
