In [6]:
#Örnek 2.10 – flatten(), flat(), ravel() fonskiyonları

import numpy as np

x = np.arange(10).reshape(5,2)
print(x)
print("*******")
print(x.flatten())
print("*******")
print(x.flat[2])
print("*******")
print(x.ravel())
print("*******")
x.ravel()[2]=100
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
*******
[0 1 2 3 4 5 6 7 8 9]
*******
2
*******
[0 1 2 3 4 5 6 7 8 9]
*******
[[  0   1]
 [100   3]
 [  4   5]
 [  6   7]
 [  8   9]]
