In [5]:
# Örnek 2.16 - ndarray.insert() fonskiyonu

import numpy as np

x = np.array([[1, 2],[5, 6]])
print(np.insert(x,1,100))
print("******")
print(np.insert(x,1,100,axis=1))
print("******")
print(np.insert(x,2,[[100],[101],[102]],axis=1))
print("******")
print(np.insert(x,1,[[100,101]],axis=0))

[  1 100   2   5   6]
******
[[  1 100   2]
 [  5 100   6]]
******
[[  1   2 100 101 102]
 [  5   6 100 101 102]]
******
[[  1   2]
 [100 101]
 [  5   6]]
