In [14]:
#Örnek 2.12 – np.concatenate() fonksiyonu

import numpy as np

x =np.array([[1,2],[3,4]])
y =np.array([[5,6]])
z =np.array([[1,2,3]])
xy = np.concatenate((x,y),axis=0)
print(xy)
print("*******")
print(np.concatenate((x,y),axis=None))
print("*******")
print(np.concatenate((xy,z.T),axis=1))

[[1 2]
 [3 4]
 [5 6]]
*******
[1 2 3 4 5 6]
*******
[[1 2 1]
 [3 4 2]
 [5 6 3]]
