In [6]:
#Örnek 2.4 – np.arange() fonksiyonu

import numpy as np

x = np.arange(5)
print(x)

y = np.arange(5,16,3,dtype = np.float)
print(y)

z = np.arange(20,16,-1)
print(z)

[0 1 2 3 4]
[ 5.  8. 11. 14.]
[20 19 18 17]
