In [10]:
# Örnek 2.17 - ndarray.delete() fonskiyonu

import numpy as np

x = np.array([[1, 2, 3],[4, 5, 6]])
print(np.delete(x,2))
print("******")
print(np.delete(x,1,axis=1))
print("******")
print(np.delete(x,0,axis=0))

[1 2 4 5 6]
******
[[1 3]
 [4 6]]
******
[[4 5 6]]
