In [6]:
#Örnek 2.20 – np.vstack() ve np.hstack() fonksiyonu

import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.vstack((x,y)))
print("*******")
print(np.hstack((x,y)))
print("*******")

a = np.array([[1, 2],[3,4]])
b = np.array([[4, 5],[6,7]])
print(np.vstack((a,b)))
print("*******")
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
*******
[1 2 3 4 5 6]
*******
[[1 2]
 [3 4]
 [4 5]
 [6 7]]
*******
[[1 2 4 5]
 [3 4 6 7]]
