In [5]:
#Örnek 2.14 – np.unique() fonksiyonu

import numpy as np

x = np.array([2,3,2,5,6,8,2,8])
print(np.unique(x))
print("******")
print(np.unique(x,return_inverse=True))
print("******")
print(np.unique(x,return_index=True))

[2 3 5 6 8]
******
(array([2, 3, 5, 6, 8]), array([0, 1, 0, 2, 3, 4, 0, 4], dtype=int64))
******
(array([2, 3, 5, 6, 8]), array([0, 1, 3, 4, 5], dtype=int64))
