In [2]:
#Örnek 2.2 – np.array() fonksiyonu

import numpy as np

pyListesi = [1, 2, 3]
x = np.array(pyListesi)
print(x)
print("****")
y = np.array([[3,5],[2,6]])
print(y)
print("****")
z =np.array([1,2,3], ndmin=2)
print(z)

[1 2 3]
****
[[3 5]
 [2 6]]
****
[[1 2 3]]
