In [26]:
#Örnek 2.5 – np.random() fonksiyonu

import numpy as np

x = np.random.randint(0,5,size=6)
print(x)
print("*******")
y = np.random.randint(0,5,size=(3,2))
print(y)
print("*******")
z = np.random.randint(20,size=5)
print(z)
print("*******")
t = np.random.randint(1, [6, 8, 10])
print(t)

[0 4 3 2 0 1]
*******
[[4 4]
 [0 2]
 [2 3]]
*******
[ 0  2  6  9 10]
*******
[3 2 5]
