In [39]:
#Örnek 2.13 – np.sort() fonksiyonu

import numpy as np

x = np.array([5,10,8])
print(np.sort(x))
print("******")
print(x)
print("******")

y = np.array([[1,5],[9,3]])
print(np.sort(y,axis=None))
print("******")

print(np.sort(y,axis=0))
print("******")

print(np.sort(y,axis=-1))

[ 5  8 10]
******
[ 5 10  8]
******
[1 3 5 9]
******
[[1 3]
 [9 5]]
******
[[1 5]
 [3 9]]
******
