In [1]:
#Örnek 2.19 – np.stack() fonksiyonu

import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.stack((x,y),axis=0))
print("*******")
print(np.stack((x,y),axis=-1))
print("*******")

a = np.array([[1, 2],[3,4]])
b = np.array([[4, 5],[6,7]])
print(np.stack((a,b),axis=-1))
print("*******")
print(np.stack((a,b),axis=1))
print("*******")
print(np.stack((a,b),axis=0))

[[1 2 3]
 [4 5 6]]
*******
[[1 4]
 [2 5]
 [3 6]]
*******
[[[1 4]
  [2 5]]

 [[3 6]
  [4 7]]]
*******
[[[1 2]
  [4 5]]

 [[3 4]
  [6 7]]]
*******
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
