In [38]:
# Örnek 2.15: ndarray.append() fonskiyonu

import numpy as np

x = np.array([[1, 2],[5, 6]])
print(np.append(x,[5,6]))
print("******")
print(np.append(x,[[9,10]],axis=0))
print("******")
print(np.append(x,[[20,21],[22,23]],axis=0))
print("******")
print(np.append(x,[[20],[23]],axis=1))
print(np.unique(x))

[1 2 5 6 5 6]
******
[[ 1  2]
 [ 5  6]
 [ 9 10]]
******
[[ 1  2]
 [ 5  6]
 [20 21]
 [22 23]]
******
[[ 1  2 20]
 [ 5  6 23]]
******
