In [1]:
#Örnek 2.11: ndarray.transpose(),ndarray.T fonksiyonları
    
import numpy as np

x = np.array([[2,3,2,5],[6,8,2,8]])
print(x.transpose())
print("*****")
print(x.T)
print("*****")
print(x)

[[2 6]
 [3 8]
 [2 2]
 [5 8]]
*****
[[2 6]
 [3 8]
 [2 2]
 [5 8]]
*****
[[2 3 2 5]
 [6 8 2 8]]
