In [24]:
#Örnek 2.1 – np.empty(),np.zeros(), np.ones() fonksiyonları

import numpy as np
x = np.empty([2,3], dtype = int) 
print(x)
print("*******")
y = np.empty([3,5])
print(y)
print("*******")
k = np.ones(6)
print(k)
print("*******")
m = np.zeros([2,3,2], dtype = np.uint8)
print(m)

[[2040661920        431          0]
 [         0          1  168439397]]
*******
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
*******
[1. 1. 1. 1. 1. 1.]
*******
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
