In [14]:
# Örnek 2.12: ndarray.flip() fonskiyonu

import numpy as np

x = np.array([[1, 2, 3], [8, 9, 10],[15,16,17]])
print(x)
print("*******")
print(np.flip(x))
print("*******")
print(np.flip(x,0))
print("*******")
print(np.flip(x,1))
print("*******")
print(np.flip(x[2]))
print("*******")

[[ 1  2  3]
 [ 8  9 10]
 [15 16 17]]
*******
[[17 16 15]
 [10  9  8]
 [ 3  2  1]]
*******
[[15 16 17]
 [ 8  9 10]
 [ 1  2  3]]
*******
[[ 3  2  1]
 [10  9  8]
 [17 16 15]]
*******
[17 16 15]
*******
